# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44593317bb117f0ab636d39b92d5f13ffde8c74d30818380b7d014a65803ff56f2a37be73f87b5ac15d246f62d0e7c35cd171fd2f8ec4d9b69bbcec128d405c5

test:
  secret_key_base: d37c4bcf6cdb0e22f27d24de16ef7007df149051bf644ce836d285fffcc8376eb1a1c0a1efa073d11cd3f5337609b45087843e2df7eb089f329c40cd14c71bc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
